spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/chatme?authSource=admin&authMechanism=SCRAM-SHA-1
      host: localhost
      port: 27017
      database: chatme
      username: admin
      password: admin
      authentication-database: admin

