spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:chatme
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/chatme?authSource=admin&authMechanism=SCRAM-SHA-1
      host: localhost
      port: 27017
      database: chatme
      username: admin
      password: admin
      authentication-database: admin

